#!/usr/bin/perl

# Copyright (C) 2004-2010, Jonathan Koren <jonathan@jonathankoren.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies of the Software, its documentation and marketing & publicity
# materials, and acknowledgment shall be given in the documentation, materials
# and software packages that this Software was used.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\
#

# gnome_imlibsetroot
#
# Provides GNOME support for imlibsetroot.  Usage is identical to imlibsetroot.

# Created                       CDT 2004		Jonathan Koren
# Modified: Thu Apr  1 00:25:24 PDT 2010		Jonathan Koren
#             Added support for filenames with spaces.


$IMLIBSETROOT = "/usr/bin/imlibsetroot";
$GCONFTOOL = "/usr/bin/gconftool-2";

$stored_file = "$ENV{HOME}/.background-".time.".png";
$found_store = 0;
for ($i = 0; $i <= $#ARGV; $i++)
{
    if ($ARGV[$i] eq "--store")
    {
        if (($ARGV[$i+1] !~ /^-/) && (($i + 1) <= $#ARGV))
        {
            $stored_file = $ARGV[$i+1];
        }
        else
        {
            $stored_file = $ENV{HOME} . "/.background.png";
        }

        $found_store = 1;
        last;
    }
}

# Ensure a full pathname
if ($stored_file !~ m!^/!)
{
    $stored_file = $ENV{PWD} . "/" . $stored_file;
}

# Force image storing, because things that use GConf (e.g. Nautilus) insist
# on using filenames.
if (! $found_store)
{
    # unshift these individually, because we want to escape spaces 
    # in filenames later
    unshift(@ARGV, $stored_file);
    unshift(@ARGV, "--store");
}

$old_filename = `$GCONFTOOL -g /desktop/gnome/background/picture_filename`;
if ((-e $old_filename) &&
    ($old_filename =~ m!$ENV{HOME}/\.background-\d+\.png!))
{
    unlink $old_filename;
}

system("$IMLIBSETROOT @ARGV");
system("$GCONFTOOL --type string -s /desktop/gnome/background/picture_options stretched");
system("$GCONFTOOL --type string -s /desktop/gnome/background/picture_filename $stored_file");
